version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
    working_directory: ~/repo

    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'
      
      - run: 'sudo npm install -g newman'
        #HTML Report
      - run: 'sudo npm install -g newman-reporter-html'    
          
      - run: 'sudo npm install -g newman-reporter-htmlfull'        
      - run: 'sudo npm install -g newman-reporter-htmlextra'                 
      - run: 'ls -la'

      # This should go into custom primary image, here's only for the sake of explanation
      #API Testing TC 1
      - run: 'newman run ./resources/TC_01.json --environment ./resources/UATenvironment.json -r cli,htmlextra --reporter-htmlextra-export ./results/'
   
         # Save artifacts
      - store_artifacts:
          path: ~/
          destination: build
      
  test:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'
            - run: 'sudo npm install -g newman'
        #HTML Report
      - run: 'sudo npm install -g newman-reporter-html'    
          
      - run: 'sudo npm install -g newman-reporter-htmlfull'        
      - run: 'sudo npm install -g newman-reporter-htmlextra'                 
      - run: 'ls -la'

      # This should go into custom primary image, here's only for the sake of explanation
      #API Testing TC 1
      - run: 'newman run ./resources/TC_02.json --environment ./resources/UATenvironment.json -r cli,htmlextra --reporter-htmlextra-export ./results/'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



