version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "hello TC1"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello TC2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



