version: 2
jobs:
  TC_01:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
    working_directory: ~/repo

    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'
      - run: 'sudo npm install -g newman'
      - run: 'sudo npm install -g newman-reporter-html' 
      - run: 'sudo npm install -g newman-reporter-htmlfull'        
      - run: 'sudo npm install -g newman-reporter-htmlextra'                 
      - run: 'ls -la'
      #API Testing TC 2
      - run: 'newman run ./resources/TC_13.json --environment ./resources/UATenvironment.json -r cli,htmlextra --reporter-htmlextra-export ./results/'
         # Save artifacts
      - store_artifacts:
          path: ~/
          destination: build
      
  TC_02:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'
      - run: 'sudo npm install -g newman'
      - run: 'sudo npm install -g newman-reporter-html' 
      - run: 'sudo npm install -g newman-reporter-htmlfull'        
      - run: 'sudo npm install -g newman-reporter-htmlextra'                 
      - run: 'ls -la'
      #API Testing TC 2
      - run: 'newman run ./resources/TC_13.json --environment ./resources/UATenvironment.json -r cli,htmlextra --reporter-htmlextra-export ./results/'
      - store_artifacts:
          path: ~/
          destination: build
workflows:
  version: 2
  build_and_test:
    jobs:
      - TC_01
      - TC_02



