version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
    working_directory: ~/repo

    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'
  test:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'sudo npm i -g npmignore'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



